plugins {
    id 'com.android.application'
}

android {
    namespace 'com.supaelfy.prismpulse3d'
    compileSdk 35

    defaultConfig {
        applicationId 'com.supaelfy.prismpulse3d'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '1.1-native'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
